# Generated by Django 5.2 on 2025-11-06 03:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('params', models.JSONField(blank=True, default=dict)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('dataset_path', models.CharField(blank=True, default='', max_length=512)),
                ('artifact_path', models.CharField(blank=True, default='', max_length=512)),
                ('progress', models.FloatField(default=0.0)),
                ('error', models.TextField(blank=True, default='')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_jobs', to='network.networkgraph')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
