# Generated by Django 5.2 on 2025-11-15 14:22

import os
import uuid
from django.db import migrations, models


def populate_ids_and_sizes(apps, schema_editor):
    LayerNode = apps.get_model('network', 'LayerNode')
    Edge = apps.get_model('network', 'Edge')
    ModelImportJob = apps.get_model('network', 'ModelImportJob')

    for node in LayerNode.objects.all().iterator():
        update_fields = []
        if not node.client_id:
            raw = node.id.split(':', 1)[1] if ':' in node.id else node.id
            node.client_id = raw
            update_fields.append('client_id')
        if not node.stable_id:
            node.stable_id = uuid.uuid4()
            update_fields.append('stable_id')
        if update_fields:
            node.save(update_fields=update_fields)

    for edge in Edge.objects.all().iterator():
        update_fields = []
        if not edge.client_id:
            raw = edge.id.split(':', 1)[1] if ':' in edge.id else edge.id
            edge.client_id = raw
            update_fields.append('client_id')
        if not edge.stable_id:
            edge.stable_id = uuid.uuid4()
            update_fields.append('stable_id')
        if update_fields:
            edge.save(update_fields=update_fields)

    for job in ModelImportJob.objects.all().iterator():
        if job.upload_size_bytes:
            continue
        path = job.stored_path
        if not path:
            continue
        try:
            size = os.path.getsize(path)
        except OSError:
            size = 0
        job.upload_size_bytes = size
        job.save(update_fields=['upload_size_bytes'])


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_trainingjob_status_modelimportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='edge',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='edge',
            name='stable_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='layernode',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='layernode',
            name='stable_id',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='modelimportjob',
            name='upload_size_bytes',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='edge',
            index=models.Index(fields=['graph', 'client_id'], name='edge_graph_client_idx'),
        ),
        migrations.AddIndex(
            model_name='layernode',
            index=models.Index(fields=['graph', 'client_id'], name='layernode_graph_client_idx'),
        ),
        migrations.RunPython(populate_ids_and_sizes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='edge',
            name='stable_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='layernode',
            name='stable_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
