
"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')   # loads backend-django/.env into os.environ


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Read sensitive values from environment variables. Provide a fallback only for
# local development. Replace in production via environment.
SECRET_KEY = os.getenv(
    "SECRET_KEY",
    "django-insecure-xihgu%&aw56df2+)q=z3z!9#+chb*yx)ao9skcp*!(#@z(l=jf",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Control via env var: set DEBUG=1/true in development, unset/false in prod
DEBUG = str(os.getenv("DEBUG", "False")).lower() in ("1", "true", "yes", "on")

# Configure allowed hosts via comma-separated ENV value, e.g. ALLOWED_HOSTS=example.com,api.example.com
allowed_hosts_env = os.getenv("ALLOWED_HOSTS", "")
ALLOWED_HOSTS = [h.strip() for h in allowed_hosts_env.split(",") if h.strip()] if allowed_hosts_env else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

INSTALLED_APPS += ['corsheaders', 'rest_framework', 'network', 'rest_framework.authtoken']

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}
# Use a custom exception handler to convert library-specific exceptions
# (e.g. GraphValidationError) into clean API responses.
REST_FRAMEWORK.setdefault('EXCEPTION_HANDLER', 'network.api_exception_handler.custom_exception_handler')


LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "stream": "ext://sys.stdout",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
    "loggers": {
        # keep module loggers at DEBUG during development
        "network": {
            "handlers": ["console"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# PostgreSQL configuration (optional). If POSTGRES_HOST is set, we switch to
# Postgres and configure search_path to use a separate schema for the Django
# application to avoid interfering with ASP.NET-owned tables.
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
if POSTGRES_HOST:
    POSTGRES_PORT = int(os.getenv("POSTGRES_PORT", 5432))
    POSTGRES_DB = os.getenv("POSTGRES_DB", "maid")
    POSTGRES_USER = os.getenv("POSTGRES_USER", "maid")
    POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD", "")
    # Schema to use for Django objects (keep separate from ASP.NET schema)
    DATABASE_SCHEMA = os.getenv("POSTGRES_SCHEMA", "django_app")

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "NAME": POSTGRES_DB,
            "USER": POSTGRES_USER,
            "PASSWORD": POSTGRES_PASSWORD,
            "HOST": POSTGRES_HOST,
            "PORT": POSTGRES_PORT,
            # Keep connections alive for performance in web workers
            "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", 600)),
            # Set the search_path so Django uses the dedicated schema by default
            "OPTIONS": {
                "options": f"-c search_path={DATABASE_SCHEMA},public",
            },
        }
    }


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ORIGIN_ALLOW_ALL = str(os.getenv("CORS_ORIGIN_ALLOW_ALL", "False")).lower() in ("1", "true", "yes", "on")

# Directory to store model artifacts and job uploads. Can be overridden via ENV.
ARTIFACTS_DIR = Path(os.getenv("ARTIFACTS_DIR")) if os.getenv("ARTIFACTS_DIR") else BASE_DIR / "artifacts"

# Upload limits and allowed extensions (comma-separated)
MAX_UPLOAD_SIZE = int(os.getenv("MAX_UPLOAD_SIZE", 10 * 1024 * 1024))  # bytes, default 10 MB
ALLOWED_UPLOAD_EXTENSIONS = [e.strip() for e in os.getenv("ALLOWED_UPLOAD_EXTENSIONS", ".csv,.keras,.h5,.zip").split(",") if e.strip()]

# Import job safeguards
IMPORT_JOB_MAX_PENDING_PER_USER = int(os.getenv("IMPORT_JOB_MAX_PENDING_PER_USER", 3))
IMPORT_JOB_ALLOWED_EXTENSIONS = [
    e.strip()
    for e in os.getenv("IMPORT_JOB_ALLOWED_EXTENSIONS", ".keras,.h5,.zip").split(",")
    if e.strip()
]
IMPORT_JOB_PENDING_STORAGE_LIMIT_MB = int(os.getenv("IMPORT_JOB_PENDING_STORAGE_LIMIT_MB", 0))

# Celery / Redis configuration
DEFAULT_REDIS_URL = "redis://redis:6379/0"
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", DEFAULT_REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_TASK_ALWAYS_EAGER = str(os.getenv("CELERY_TASK_ALWAYS_EAGER", "False")).lower() in {"1", "true", "yes", "on"}
CELERY_TASK_EAGER_PROPAGATES = True
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True

# Artifact cleanup policy: number of days to retain saved artifacts before pruning
ARTIFACT_RETENTION_DAYS = int(os.getenv("ARTIFACT_RETENTION_DAYS", 30))

